import SwiftUI

@main
struct NotedApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var body: some Scene {
        MenuBarExtra {
            NotedMenuBarView(appDelegate: appDelegate)
        } label: {
            // Custom template glyph rather than an SF Symbol — square.and.pencil is what half
            // the menu bar already uses. Generated by tools/generate-icons.swift.
            Image("MenuBarGlyph")
        }

        Settings {
            SettingsView()
        }
    }
}
