import SwiftUI

@main
struct NotedApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    @ObservedObject private var ingest = ArticleIngestService.shared
    @ObservedObject private var pomodoro = PomodoroTimer.shared

    var body: some Scene {
        MenuBarExtra {
            NotedMenuBarView(appDelegate: appDelegate)
        } label: {
            // Custom template glyph rather than an SF Symbol — square.and.pencil is what half
            // the menu bar already uses. Generated by tools/generate-icons.swift.
            Image("MenuBarGlyph")
            // Ingestion runs for minutes; showing the figure here means it can be tracked
            // without opening the menu at all.
            if let percent = ingest.activePercent {
                Text("\(percent)%")
            } else if let clock = pomodoro.menuBarTitle {
                Text(clock)
            }
        }

        Settings {
            SettingsView()
        }
    }
}
